# -*- coding: utf-8 -*-
"""etl_stock.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAMR6GKDnW6qR5DA3baTOXdGYfYdMziV
"""

import yfinance as yf
import pandas as pd
from datetime import datetime

# 1. EXTRACT: saham yang di ambil menggunakan kode JK
saham_list = ['BBCA.JK', 'TLKM.JK', 'GOTO.JK']
semua_data = []

print("Mulai mengambil data...")
for saham in saham_list:
    ticker = yf.Ticker(saham)
    df = ticker.history(period="1d") # data 1 hari terakhir

    # TAMBAH KOLOM NAMA SAHAM
    df['Ticker'] = saham
    semua_data.append(df)

# Gabung SEMUA DATA MENJADI SATU FRAME
df_master = pd.concat(semua_data)

# 2. TRANSFORM: Rapikan tabel
df_master.reset_index(inplace=True)
# Buang kolom untuk analisa dasar
df_master = df_master[['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume']]

# Tambahkan kolom waktu kapan script ini dijalankan (penting untuk tracking ETL)
df_master['ETL_Timestamp'] = datetime.now()

print("Data berhasil di-extract dan di-transform!")
print(df_master)

import sqlite3

# Buka koneksi ke database SQLite
conn = sqlite3.connect('market_data.db')
cursor = conn.cursor()

# 3. LOAD: Masukkan DataFrame ke dalam tabel database bernama 'daily_prices'
# if_exists='append' berarti jika script dijalankan besok, datanya akan ditambahkan ke bawah, tidak ditimpa.
df_master.to_sql('daily_prices', conn, if_exists='append', index=False)

print("Data berhasil di-load ke Database market_data.db!")

# Mari kita tes Query pakai SQL langsung dari Python untuk membuktikan datanya masuk
kueri_cek = pd.read_sql_query("SELECT * FROM daily_prices", conn)
display(kueri_cek)

# Tutup koneksi (Best Practice)
conn.close()
